# Makefile for Python project

# Variables
PYTHON = python
PIP = pip

# Targets
.PHONY: install run clean

install:
	$(PIP) install -r requirements.txt

run:
	$(PYTHON) your_script.py

clean:
	rm -rf __pycache__
